// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqs8xXHRnAY7lUbfgOEWJazRL4U1Quuak',
    appId: '1:127117263525:web:4a51f98d43739c80b3c34c',
    messagingSenderId: '127117263525',
    projectId: 'centi-crensento',
    authDomain: 'centi-crensento.firebaseapp.com',
    storageBucket: 'centi-crensento.appspot.com',
    measurementId: 'G-KGJVJRSRN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl4bUm4Hs_LPNgTgrtmZXrh180NaftgHc',
    appId: '1:127117263525:android:a67339ef45987288b3c34c',
    messagingSenderId: '127117263525',
    projectId: 'centi-crensento',
    storageBucket: 'centi-crensento.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATWzU2fWy_V1QB4OEhfTjCOl6qG7yxMuk',
    appId: '1:127117263525:ios:8d29584d0d3124dcb3c34c',
    messagingSenderId: '127117263525',
    projectId: 'centi-crensento',
    storageBucket: 'centi-crensento.appspot.com',
    iosBundleId: 'com.gytx.centiCresento',
  );
}
